### ISSUE TITLE
Death Timer does not start

### ISSUE THREAD

**Issue by DomePlaysHD** [Stuyk/altv-athena-issues#54]
### Description of the problem

The death timer does not start after the first death.

### Reproduction steps

Use /sethealth 0 player_id

### Expected behaviour

-

### Additional context

Console Log:

[18:17:11][Error] [V8] Exception at core:client/utility/timers.js:63
[18:17:11][Error]               alt.clearInterval(intervalNumber);
[18:17:11][Error]   Error: Timer with that id does not exist
    at Function.clearInterval (client/utility/timers.js:63:17)
    at handleMetaChange (plugins/core-death/client/index.js:34:19)
[18:17:11][Error] Error: Timer with that id does not exist

### Version

3.4.0

**Comment by Stuyk** [comment]
Investigating

**Comment by Stuyk** [comment]
Resolved in `3.5.0`
