### ISSUE TITLE
Death System doesnt work well

### ISSUE THREAD

**Issue by grecjaxd** [Stuyk/altv-athena-issues#55]
### Description of the problem

Death System works fine after the first death or joining to the server. The problem is that you are able to walk and dont have a dark death screen with a timer and the ability to teleport after using the revive command or teleport to the hospital and by killing yourself for more than once. The System changes your IsDead state in the database to true, but thats it. 

### Reproduction steps

kill yourself then teleport to hospital or use revive command then kill yourself again and again

### Expected behaviour

.

### Additional context

[18:57:13][Error] [V8] Exception at core:client/utility/timers.js:63
[18:57:13][Error]               alt.clearInterval(intervalNumber);
[18:57:13][Error]   Error: Timer with that id does not exist
    at Function.clearInterval (client/utility/timers.js:63:17)
    at handleMetaChange (plugins/core-death/client/index.js:31:19)
[18:57:13][Error] Error: Timer with that id does not exist

After using revive command even when you are "DEAD" (only in database tho)

### Version

3.5.0

**Comment by Stuyk** [comment]
@grecjaxd Are you sure you have the latest changes?

**Comment by grecjaxd** [comment]
Im

**Comment by Stuyk** [comment]
@grecjaxd lm?

**Comment by grecjaxd** [comment]
im sure

**Comment by Stuyk** [comment]
Can't reproduce:

https://gfycat.com/HeavyCheerfulGeese
